### ISSUE TITLE
Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'

### ISSUE THREAD

**Issue by shijianzhong** [JamesBroadberry/deno-bcrypt#19] opened 2021-05-13 09:17 UTC
error: TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:18:23

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:50:23

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:83:23

**Comment by JamesBroadberry** [comment] 2021-05-13 09:20
Duplicate of #18 

The fix is to run with `--allow-net --unstable` arguments

**Closed by JamesBroadberry** 2021-05-13 09:20 UTC
