### ISSUE TITLE
Subresource check failed using lock

### ISSUE THREAD

**Issue by kevinhassan** [JamesBroadberry/deno-bcrypt#4] opened 2020-06-22 22:07 UTC
Hello, 

Thanks for this lib but I'm currently facing with an issue. I'm using `lock.json` feature from Deno to check package integrity. But when I used a function from Bcrypt package (like `bcrypt.hash()`) the following issue is printed : `Subresource integrity check failed --lock=lock.json
https://deno.land/x/bcrypt/worker.ts` and the server is down 😞 

**Info :** 
**OS**: MacOS v10.15.5
**Deno**: 1.1.1
**deno-bcrypt**: `6ed1ba413208fa23109f5055fc58eb5f62fc6cee863142b66e7b90be3f8bab4b`
**Command executed** : `deno run --allow-net --allow-env --allow-read --allow-write --allow-plugin --lock lock.json --inspect=127.0.0.1:9229 --unstable index.ts`

**Comment by JamesBroadberry** [comment] 2020-06-23 19:36
Hey,

Thanks for raising an issue. 

I've not used the integrity checking in Deno before but from their docs, have you tried updating the lock file?

The file hash may have changed between versions and if you haven't specified one when importing the module, you can specify a version like so:
`import * as bcrypt from "https://deno.land/x/bcrypt@v0.2.1/mod.ts";`

Let me know if you still have issues but it doesn't sound like this is related to this module specifically. 

Thanks! 🙂

**Comment by kevinhassan** [comment] 2020-06-24 07:08
Hey ! 
I forgot to thank you for your work ! 
I retry to update my lock file with `deno cache` and I had the `0.2.1` tag. 
Each time I want to use a `async` bcrypt method the issue is printed `Subresource integrity check failed --lock=lock.json
https://deno.land/x/bcrypt/worker.ts`.  Maybe the issue is caused by the use of worker 🤔 . 

In any way, I'm new in Deno so right now I can just share information I have 😞 .

**Comment by JamesBroadberry** [comment] 2020-06-28 19:30
Hey,

Sorry for the late response. I'll have a look into this at some point this week and try to replicate it myself.
If there's anything I can do to help, I will.

You might be able to have some luck by asking in the Deno discord if you need a solution faster? I'm just a little busy at the moment.

Thanks ☺

**Comment by kevinhassan** [comment] 2020-06-29 08:10
Hello, 
It's not urgent at all 😃. 
I will investigate on my own and maybe try to make a PR to fix this issue (I need to upgrade my skill on Deno before 😂 )

**Comment by JamesBroadberry** [comment] 2020-07-02 16:59
Hey,

So I found your repo (deno-API) and could replicate the issue you're having.
The issue is that since you created the lock.json, the version of bCrypt has updated.

The way you prevent this is by changing your deps.ts to include a specific version, like so:

`export * as bcrypt from "https://deno.land/x/bcrypt@v0.2.1/mod.ts";`
instead of
`export * as bcrypt from "https://deno.land/x/bcrypt/mod.ts";`

Or, if you just want to update your lock.json to the latest version of all of your libraries, you can add --lock-write to the command when building locally (not when running in production).
`deno run --unstable --allow-net --allow-read --allow-env --allow-write --allow-plugin --lock=lock.json --lock-write index.ts`

Let me know if I've explained this poorly or you need more help with it.

If this fixes your issue, please let me know so I can close it.

Thanks again! 👍

**Comment by kevinhassan** [comment] 2020-07-06 08:31
Hi, 
Thanks for your update, I didn't have time to investigate, so much work to do... 
I will soon and then I'll give you feedbacks 😄

**Comment by JamesBroadberry** [comment] 2020-07-22 18:24
Hi @kevinhassan, due to the inactivity on this issue and me not being able to replicate it, I'm going to close it for now. If you can produce steps (maybe an example repo?) that can reproduce this, please feel free to create another issue.

Thanks,
James

**Closed by JamesBroadberry** 2020-07-22 18:24 UTC
